version: '3.8'

services:
  web:
    build: .
    volumes:
       - ./fastapi_core:/code/fastapi_core/
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn fastapi_core.app:app --host 0.0.0.0 --reload'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn fastapi_core.main:app --host 0.0.0.0 --reload'

    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://CourseHunter:CourseHunter@db:5432/CourseHunter
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=CourseHunter
      - POSTGRES_PASSWORD=CourseHunter
      - POSTGRES_DB=CourseHunter
  
  admin:
    build: .
    volumes:
      - ./admin:/code/admin/
    # command: "python3 -m flask run --host=0.0.0.0 --reload"
    command: "python3 -m admin.app"
    # environment:
    #   - SYNC_DATABASE_URL=postgresql://CourseHunter:CourseHunter@db:5432/CourseHunter
    ports:
      - "5000:5000"
    # restart: on-failure
    depends_on:
      - web

volumes:
  postgres_data:
  