version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn fastapi_core.main:app --host 0.0.0.0 --reload'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://CourseHunter:CourseHunter@db:5432/CourseHunter
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=CourseHunter
      - POSTGRES_PASSWORD=CourseHunter
      - POSTGRES_DB=CourseHunter
  
  admin:
    build: .
    volumes:
      - .:/code
    command: "python3 -m admin.app"
    ports:
      - "5000:5000"
    depends_on:
      - web

volumes:
  postgres_data:
  