"""change accounttype

Revision ID: d8ab51222cb9
Revises: de2303a9cf05
Create Date: 2022-09-28 12:12:47.477999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ab51222cb9'
down_revision = 'de2303a9cf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
