"""add active boolean field to coursefavorite

Revision ID: 0235db0ac62b
Revises: d3ec1d68496e
Create Date: 2022-10-27 11:09:59.892884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0235db0ac62b'
down_revision = 'd3ec1d68496e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_favorites', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_favorites', 'active')
    # ### end Alembic commands ###
