"""test question and answers table, lesson difficult add choices

Revision ID: 1ce99b46b148
Revises: 0235db0ac62b
Create Date: 2022-10-31 12:08:43.617154

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

DIFFICULTES = [("easy", "easy"), ("medium", "medium"), ("hard", "hard")]


# revision identifiers, used by Alembic.
revision = '1ce99b46b148'
down_revision = '0235db0ac62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_questions_id', table_name='lesson_questions')
    op.drop_table('lesson_questions')
    op.alter_column('lessons', 'difficult',
               existing_type=sa.INTEGER(),
               type_=sqlalchemy_utils.types.choice.ChoiceType(choices=DIFFICULTES),
               existing_nullable=True)
    op.add_column('test_questions', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('test_questions', sa.Column('lesson_test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_questions', 'lesson_tests', ['lesson_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_column('test_questions', 'lesson_test_id')
    op.drop_column('test_questions', 'description')
    op.alter_column('lessons', 'difficult',
               existing_type=sqlalchemy_utils.types.choice.ChoiceType(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('lesson_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lesson_questions_pkey')
    )
    op.create_index('ix_lesson_questions_id', 'lesson_questions', ['id'], unique=False)
    # ### end Alembic commands ###
