"""relationship user and account moded

Revision ID: 224918edb868
Revises: 60e9882cbb21
Create Date: 2022-09-28 12:57:03.216276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224918edb868'
down_revision = '60e9882cbb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
