"""RE_ADDED accounttype

Revision ID: 60e9882cbb21
Revises: 803ad08f0a96
Create Date: 2022-09-28 12:21:46.535432

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

TYPES = [
        ('admin', 'Admin account'),
        ('standart', 'Standart account'),
        ('premium', 'Premium account')
]

# revision identifiers, used by Alembic.
revision = '60e9882cbb21'
down_revision = '803ad08f0a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(choices=TYPES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'type')
    # ### end Alembic commands ###
