"""deleted status in rating

Revision ID: 6b3655d9a8ea
Revises: 7cbc712b521e
Create Date: 2022-11-04 13:41:46.245182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3655d9a8ea'
down_revision = '7cbc712b521e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_ratings', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_ratings', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
