"""delete accounttype

Revision ID: 803ad08f0a96
Revises: d8ab51222cb9
Create Date: 2022-09-28 12:19:17.547443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '803ad08f0a96'
down_revision = 'd8ab51222cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('type', postgresql.ENUM('standart', 'premium', name='accounttype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
