"""video field added to course table

Revision ID: 85c994faabb5
Revises: 1ce99b46b148
Create Date: 2022-11-01 16:37:59.501697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c994faabb5'
down_revision = '1ce99b46b148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video')
    # ### end Alembic commands ###
