"""admin type added in account types

Revision ID: 91ecc47aa180
Revises: 6e54f9e48b1c
Create Date: 2022-09-27 12:59:58.886193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ecc47aa180'
down_revision = '6e54f9e48b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
