"""relationship added in user

Revision ID: c94b4fef5133
Revises: 2c3d27a01dee
Create Date: 2022-09-28 13:38:15.009576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94b4fef5133'
down_revision = '2c3d27a01dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
