"""CourseFavorite model with course user relation

Revision ID: d3ec1d68496e
Revises: ee7fc01b11b0
Create Date: 2022-10-27 10:58:11.518035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ec1d68496e'
down_revision = 'ee7fc01b11b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_favorites', type_='foreignkey')
    op.drop_column('course_favorites', 'user_id')
    # ### end Alembic commands ###
