"""course draft field, attachments in lesson, category logo, course logo upload

Revision ID: d6551c737d01
Revises: 52fb7660efff
Create Date: 2022-10-21 09:53:41.827278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6551c737d01'
down_revision = '52fb7660efff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_files_id', table_name='lesson_files')
    op.drop_table('lesson_files')
    op.add_column('categories', sa.Column('logo', sa.String(length=300), nullable=True))
    op.add_column('courses', sa.Column('logo', sa.String(length=300), nullable=True))
    op.add_column('courses', sa.Column('draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'draft')
    op.drop_column('courses', 'logo')
    op.drop_column('categories', 'logo')
    op.create_table('lesson_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lesson_files_pkey')
    )
    op.create_index('ix_lesson_files_id', 'lesson_files', ['id'], unique=False)
    # ### end Alembic commands ###
