"""course video field added

Revision ID: ee7fc01b11b0
Revises: d6551c737d01
Create Date: 2022-10-21 10:01:09.002536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7fc01b11b0'
down_revision = 'd6551c737d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('video', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'video')
    # ### end Alembic commands ###
