"""added status in rating

Revision ID: f6a2b9e556a1
Revises: 6b3655d9a8ea
Create Date: 2022-11-04 13:42:44.962603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a2b9e556a1'
down_revision = '6b3655d9a8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
